apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    app.kubernetes.io/instance: python-helloworld
  name: python-helloworld-service
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-helloworld
  sessionAffinity: None
  type: ClusterIP
